version: '3.9'
services:
  redis:
    image: redislabs/redismod
    restart: always
    container_name: redis
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - fsv-net
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: wcj520600
    ports:
      - "3306:3306"
    networks:
      - fsv-net
  minio:
    image: "quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=12345678
      #- MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      #- MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - fsv-net
networks:
  fsv-net:
    driver: bridge