server:
  undertow:
    buffer-size: 16384
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256
    accesslog:
      # 是否开启访问日志
      enabled: true
  # 端口
  port: 8080
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: fsv
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: true
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      data-locations:
        - classpath:sql/role.sql
        - classpath:sql/user.sql
      mode: always
      username: root
      password: wcj520600
      continue-on-error: true
      encoding: UTF-8
  task:
    execution:
      pool:
        core-size: 8
        max-size: 60
        keep-alive: 60s
        queue-capacity: 500
        allow-core-thread-timeout: true
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtps
    username: 473991883@qq.com
    password: vqytvlyecfapcajj
    properties:
      mail.smtp.ssl.enable: true

fsv:
  options:
    logging: true